### ISSUE TITLE
bug(perp): perp cannot exit position when setting specifically the remain shares amount

### ISSUE THREAD

**Issue by AgentSmithMatrix** [NibiruChain/nibiru#869] opened 2022-09-06 10:19 UTC
It looks like if I have 100000000000000000000nibiru for example, and I want to exit my position of exactly that amount it does not allow to get 
out.

**Comment by helder-moreira** [comment] 2022-10-27 15:24
@AgentSmithMatrix @NibiruHeisenberg I can't reproduce this. The steps I followed were:

1. Open a position
2. Add margin to position
3. Remove margin from position
4. Close position

All worked fine.

The only thing that does not work its trying to remove all the margin from the position, which shows the error `not enough free collateral`. I guess this is expected, as you can't remove everything you put in there without paying at least fees.

**Comment by helder-moreira** [comment] 2022-11-29 15:37
> @helder-moreira do you have the values you used? I just tested this against localnet and it's working properly:
> 
> ```shell
> nibid tx perp open-position buy ubtc:unusd 1 500 0 --from validator  --keyring-backend test --chain-id nibiru-localnet-0 -y --broadcast-mode block --gas 99999999999
> nibid tx perp add-margin ubtc:unusd 100unusd --from validator  --keyring-backend test --chain-id nibiru-localnet-0 -y --broadcast-mode block --gas 99999999999
> nibid tx perp remove-margin ubtc:unusd 100unusd --from validator  --keyring-backend test --chain-id nibiru-localnet-0 -y --broadcast-mode block --gas 99999999999
> nibid tx perp close-position ubtc:unusd --from validator  --keyring-backend test --chain-id nibiru-localnet-0 -y --broadcast-mode block --gas 99999999999
> ```

I don't. But I tried multiple combinations and saw no issue.

**Comment by jgimeno** [comment] 2022-12-08 20:50
Can we close it ?

**Comment by Unique-Divine** [comment] 2023-10-23 16:10
Seems this was fixed

**Closed as completed by Unique-Divine** 2023-10-23 16:10 UTC
Labels: good first issue
