### ISSUE TITLE
[bug] user liked a tweet and was in pending queue. task is expired but is not in pending or completed section, just disappeared

### ISSUE THREAD

**Issue by brandonsuzuki** [NibiruChain/nibiru#1794] opened 2024-02-13 01:39 UTC
Twitter handle: mr_dunock

**Comment by cgilbe27** [comment] 2024-02-13 13:55
Duplicate of https://github.com/NibiruChain/home-site/issues/285

**Closed by cgilbe27** 2024-02-13 13:55 UTC
